title: David Yang
description: This is  David Yang's Blog

url: http://davidyangcool.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate,jekyll-admin]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Tags
   url: /tags
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: davidyangcool
   twitter: DavidyangCool
   facebook: davidyang.cool
   email: davidyang_cool@icloud.com

google_analytics: "UA-58263416-1"
